version: '3.8'
services:

  controller:
    image: ngrinder/controller
    container_name: controller
    restart: always
    hostname: ncontroller
    ports: 
      - '8888:80'
      - '16001:16001'
      - '12000-12009:12000-12009'
    volumes:
    - ./ngrinder-controller:/opt/ngrinder-controller

  agent:
    image: ngrinder/agent
    container_name: nagent
    restart: always
    hostname: agent
    depends_on:    
      - controller
