version: '3.8'
services:

  controller:
    image: ngrinder/controller
    container_name: controller
    restart: always
    hostname: controller
    ports: 
      - '8888:80'
      - '16001:16001'
      - '12000-12009:12000-12009'
    volumes:
    - ./docker-ngrinder-controller/ngrinder-controller-date:/opt/ngrinder-controller

  agent:
    image: ngrinder/agent
    container_name: agent
    restart: always
    hostname: agent
    depends_on:    
      - controller
