version: '3.8'
services:

  controller:
    image: ngrinder/controller
    container_name: ncontroller
    restart: always
    hostname: controller
    ports: 
      - '8888:80'
      - '16001:16001'
      - '12000-12009:12000-12009'
    volumes:
    - ./ngrinder-controller-date:/opt/ngrinder-controller
