version: '3.8'
services:

  agent:
    image: ngrinder/agent
    container_name: agent
    restart: always
    hostname: agent
    volumes:
      - ./ngrinder-agent:/opt/ngrinder-agent
    network_mode: 'host'
