version: '3.8'
services:

  agent1:
    image: ngrinder/agent:${NGRINDER_VERSION}
    restart: always
    container_name: agent1
    hostname: agent1
    sysctls:
      - net.core.somaxconn=65000
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc:
        soft: 1024000
        hard: 1024000
      nofile:
        soft: 1024000
        hard: 1024000
    links:
      - controller:controller
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - ./ngrinder-agent-data:/opt/ngrinder-agent
      #- ./ngrinder-agent-data/agent.conf:/opt/ngrinder-agent/.ngrinder-agent/agent.conf
    network_mode: 'host'
